import sys

file = open(sys.argv[1], 'rb').read()

words = [ "African", "care", "assumption", "barrel", "angle", "chemical", "ceiling", "chain", "coast", "also", "butter", "assume", "bean", "abandon", "approve", "appoint", "attorney", "benefit", "bridge", "analyst", "ally", "blame", "all", "arrive", "besides", "accept", "brain", "completely", "bike", "complicated", "complex", "concentration", "camp", "common", "accuse", "celebrate", "box", "cat", "above", "capture", "closely", "accompany", "chicken", "assure", "baby", "athletic", "coalition", "city", "actually", "brief", "agreement", "briefly", "afternoon", "chase", "adjust", "bet", "begin", "complaint", "acid", "book", "achievement", "bank", "band", "assistant", "clothing", "component", "apple", "celebrity", "abroad", "advance", "aggressive", "assert", "charge", "boundary", "British", "bond", "beat", "badly", "board", "alive", "brother", "circumstance", "advertising", "assignment", "bread", "agree", "attach", "bombing", "chair", "but", "bar", "artistic", "carrier", "compete", "anger", "bake", "communicate", "championship", "alliance", "awareness", "beach", "beginning", "competitive", "boy", "career", "aside", "bench", "almost", "boom", "anybody", "cause", "accurate", "adopt", "candidate", "clearly", "check", "collect", "comparison", "bunch", "being", "bother", "background", "activity", "action", "beside", "angry", "appear", "aspect", "center", "artist", "able", "celebration", "breakfast", "cheek", "boyfriend", "adequate", "commit", "associate", "central", "aim", "admission", "compare", "cold", "cigarette", "attract", "back", "catch", "company", "bad", "category", "apparent", "arise", "adolescent", "boot", "arrange", "agenda", "beyond", "air", "authority", "American", "ahead", "commercial", "buyer", "border", "car", "author", "brand", "available", "anymore", "composition", "airport", "choose", "certainly", "basis", "Arab", "comment", "become", "coal", "bite", "airline", "choice", "chip", "coffee", "blade", "ball", "apparently", "arrest", "belt", "affect", "CEO", "claim", "biological", "be", "agency", "among", "colleague", "absence", "additional", "carry", "believe", "cluster", "both", "buck", "arrival", "compose", "anxiety", "competition", "client", "budget", "broken", "brown", "coat", "carbon", "according", "access", "adapt", "climate", "ban", "accident", "actress", "awful", "absorb", "between", "after", "assist", "campus", "administrator", "abuse", "changing", "attitude", "bed", "assistance", "attractive", "amazing", "belong", "because", "commander", "advocate", "barely", "base", "by", "college", "battle", "bullet", "area", "another", "broad", "absolute", "chart", "army", "collective", "cheese", "billion", "apart", "cholesterol", "citizen"]

output = "" 
iterator = 0
while iterator < len(file):
    output += '"%s",' % words[file[iterator] % len(words)]  # Ensure index is within range
    iterator += 1

print(output)